# Generated by Django 3.2.8 on 2021-11-01 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbours', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
