# Generated by Django 3.2.8 on 2021-11-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_neighbours', '0002_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='username',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='username',
            new_name='user',
        ),
    ]
